spring:
  application:
    name: spark-networks-eureka
server:
  port: 8085
eureka:  client:    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8085/eureka