openapi: 3.0.0
info:
  description: Filter handler powered by Spark networks - client side
  version: 1.0.0-oas3
  title: Filter handler - client
tags:
- name: Filter Handler - client
  description: Pojo definition for client filter handler
paths:
  /:
    get:
      tags:
      - Login API
      summary: >-
        Api for login screen
      operationId: login
      responses:
        '200':
          description: successfull operation       
  /home:
    get:
      tags:
      - Home API
      summary: >-
        home api for person details screens
      operationId: home
      responses:
        '200':
          description: successfull operation
components:
  schemas:
    LoginRequestModel:
      properties:
        name:
          type: string
        password:
          type: string    
    PersonDetailsModel:
      properties:
        display_name:
          type: string
        password:
          type: string   
        age:
          type: integer
        job_title:
          type: string
        height_in_cm:
          type: integer
          format: int64
        city:
          type: object
          $ref: '#/components/schemas/City'
        main_photo:
          type: string
        compatibility_score:
          type: number
          format: double
        contacts_exchanged:
          type: integer
        favourite:
          type: boolean
        religion:
          type: string
    City:
      properties:
        name:
          type: string
        lat:
          type: number
          format: double
        lon:
          type: number
          format: double
    FilterHandlerResponse:
      properties:
        matches:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/PersonDetailsModel'
    FilterHandlerRequest:
      properties:
        hasPhoto:
          type: boolean
        inContact:
          type: boolean
        favorite:
          type: boolean
        compatibility:
          type: object
          $ref: '#/components/schemas/Compatibility'
        age:
          type: object
          $ref: '#/components/schemas/Age'
        height:
          type: object
          $ref: '#/components/schemas/Height'
        distance:
          type: object
          $ref: '#/components/schemas/Distance'
        user:
          type: object  
          $ref: '#/components/schemas/PersonDetailsModel'
    Distance:
      properties:
        from:
          type: number
          format: double
        to:
          type: number
          format: double
    Height:
      properties:
        from:
          type: integer
        to:
          type: integer
    Age:
      properties:
        from:
          type: integer
        to:
          type: integer
    Compatibility:
      properties:
        from:
          type: number
          format: double
        to:
          type: number
          format: double
    ResponseError:
      properties:
        errorCode:
          type: integer
        errorMessage:
          type: string       
        detailedMessage:
          type: string
        exceptionName:
          type: string
        createdAt:
          type: string