spring:
  application:
    name: spark-networks-client
server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}
  instance:
    preferIpAddress: true    